- src/locales/el.yml
Greek translations were encoded as ISO-8859-7 instead of UTF-8.
> Fix encoding

- src/locales/ja.yml
I updated the Japanese(ja) translation as part of #127
When machine translating from half width to full width, the% was changed and the variable part of the message was not working.I've fixed Japanese, but it may be better to check if there are any problems with other languages.
> update japanese(ja) translation

- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/controlbar/video_player_controlbar.html
- src/dynamics/video_player/player/player.html
- src/dynamics/video_recorder/recorder/recorder.html
- src/dynamics/video_recorder/recorder/recorder.js
- src/dynamics/video_recorder/recorder/states.js
- src/themes/video_player/cube/colors.scss
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/cube/cube-video_player_controlbar.html
- src/themes/video_player/elevate/colors.scss
- src/themes/video_player/elevate/controlbar.scss
- src/themes/video_player/elevate/elevate-video_player_controlbar.html
- src/themes/video_player/minimalist/colors.scss
- src/themes/video_player/minimalist/controlbar.scss
- src/themes/video_player/minimalist/minimalist-video_player_controlbar.html
- src/themes/video_player/minimalist/theme.scss
- src/themes/video_player/modern/controlbar.scss
- src/themes/video_player/modern/modern-video_player_controlbar.html
- src/themes/video_player/space/colors.scss
- src/themes/video_player/space/controlbar.scss
- src/themes/video_player/space/space-video_player_controlbar.html
- src/themes/video_player/theatre/colors.scss
- src/themes/video_player/theatre/controlbar.scss
- src/themes/video_player/theatre/theatre-video_player_controlbar.html
This PR introduces the following changes:
- Add `pickcovershotframe` parameter to video recorder. It allows the user to select any frame as covershot.
- Covershot selection was refactored to keep everything encapsulated on the same state.
- A new state `CovershotSelectionFromPlayer` was created to handle frame selection.
> Feature: pickcovershotframe

- demos/embed/recorder.html
- src/dynamics/video_recorder/recorder/states.js
`pickcovershotframe` should be disabled on uploader unless `snapshotfromuploader` is true.
> Fix pickcovershotframe on uploader

- src/dynamics/video_recorder/recorder/recorder.js
Reset method was not working for video uploads because it required `enumerateDevices` promise to be completed - but this promise is only called on video recordings. This PR fixes this and other errors that are thrown when recorder is reset before `enumerateDevices` promise is completed.
> Fix: reset method on video uploader

- src/dynamics/_common/audio_visualization.js
- src/dynamics/audio_player/player/player.html
- src/dynamics/audio_player/player/player.js
- src/dynamics/audio_recorder/recorder/recorder.html
- src/dynamics/audio_recorder/recorder/recorder.js
This PR fixes the following issues:
- Audio muted on player when using `visualeffectvisible` due to cross-origin issues
- Microphone echo sound when using `visualeffectvisible` after audio recording starts
- `visualeffectvisible` was being treated as string, so `ba-visualeffectvisible=false` was interpreted as "false", which is truthy and made the effect show up
- Typo on word visualization
> Fix: audio visualization bugs

- src/dynamics/video_recorder/recorder/recorder.js
- src/dynamics/video_recorder/recorder/states.js
When `allowtrim` is set to true the recorded or uploaded video can be trimmed with our trimming overlay, which uses the video player dynamic. Some users may want to use their own interface for trimming video, so this PR was created to address this use case. It introduces the following changes:
- Added new boolean parameter `trimoverlay` to allow user to hide trimming overlay. Default value is true, when set to false trimming happens by calling the trim method.
- Added new `trim` method for setting when trimmed video should start and end.
- Added new string `trim-video` that is shown when `trimoverlay` is set to false.
- Added new event `video-trimmed` which is triggered by the recorder after video is trimmed manually or using the trimming overlay. It returns trimming start and end time, …
> Feature: manual trimming

- src/dynamics/audio_player/player/player.html
- src/dynamics/audio_player/player/player.js
- src/dynamics/video_player/player/player.js
This PR introduces the following changes:
- **Video Player:** 
- Added `pauseonclick` parameter and fixed issue with player not pausing on click
- Removed some of the redundant code on `toggle_player` function
- **Audio Player:**
- Added implementation for `playonclick` parameter - the parameter existed, but didn't do anything as it wasn't implemented yet
- Added `pauseonclick` parameter
> Feature: pauseonclick parameter

- src/dynamics/audio_player/player/states.js
When clicking to retry after the request for getting audio fails the audio player would freeze and stop working. This PR fixes the issue.
> Fix audio player breaking after request fail

- src/dynamics/audio_player/player/player.js
Getting the total duration from an audio is tricky and browsers often get it wrong, this PR makes the audio player prioritize the data set on `totalduration` attribute over information that is coming from the browser.
> Fix: audio player total duration

- src/dynamics/audio_recorder/recorder/recorder.html
- src/dynamics/audio_recorder/recorder/recorder.js
- src/dynamics/audio_recorder/recorder/states.js
- src/dynamics/video_recorder/recorder/recorder.js
This PR introduces the following changes:
- Default value for `duration` on audio and video recorder is now 0 seconds.
- Audio recorder: changed duration of recorded audio from ms to s (to match uploaded audio duration / video recorder)
- Duration is now reset to 0 on `reset` and `rerecord`.
> Minor changes to recorder duration

- src/dynamics/video_recorder/recorder/recorder.js
- src/dynamics/video_recorder/recorder/states.js
This PR fixes an issue where the recorded duration kept increasing on Firefox while recording was paused. To fix this we:
- Stopped updating the duration while the recorder is paused.
- Started using the actual time difference between when the pause button is clicked until the recording starts again to get the paused duration. Before we were triggering a timer and increasing the duration based on how many times the timer was fixed, which is not quite reliable.
> [Fix] Firefox duration when recorder is paused

- src/dynamics/audio_player/player/player.js
- src/dynamics/audio_recorder/recorder/recorder.js
- src/dynamics/image_capture/capture/capture.js
- src/dynamics/video_player/player/player.js
- src/dynamics/video_recorder/recorder/recorder.js
It was not possible to override the InitialState on child dynamics. This PR fixes this.
> [Fix] Initial state on children

- src/dynamics/video_player/player/player.js
This allow us to use the attribute by calling `<ba-videoplayer ... ba-hidecontrolbar></ba-videoplayer>` instead of `<ba-videoplayer ... ba-hidecontrolbar=true></ba-videoplayer>`.
> [Video Player] Add hidecontrolbar type

- src/dynamics/video_player/player/player.js
16:9 videos are more common than 4:3, so changing the default value will cause less size "jumping" issues.
> [Video Player] Change default aspect ratio from 4:3 to 16:9

- src/dynamics/_common/sticky_handler.js
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
Sticky classes weren't being added to the correct element if the player template was modified. This PR fixes this issue.
> [Fix] [Video Player] Add sticky classes on correct element

- src/dynamics/video_player/player/player.js
- src/themes/_common/sticky.scss
Width 100% as inline style overrides the width from the sticky class. We are already adding width 100% to the player through the `ba-commoncss-full-width` class, so no need to do it inline as well.
This PR also does the following:
- Set max-width to 100% on sticky player
- Remove media query from sticky player limiting width to 50%
> [Fix] Sticky player sizing

- src/dynamics/video_player/player/player.js
For some reason setting `display: block` is messing the player height on Safari.
> [Fix] Player height on Safari desktop

- src/dynamics/ads_player/ads_controlbar/ads_controlbar.js
- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
This PR refactors how volume changes are applied, fixing the following issues:
- Sound plays for a fraction of a second when an ad is paused and unmuteonclick is enabled
- Sound changes during ad playback aren't reflected on main video content
- Volume slider on jumps around when sliding during ad playback
> [Fix] Volume issues linked to ad playback

- src/dynamics/_common/sticky_handler.js
Issue can be reproduced with the following attributes:
```
sticky: true,
floatingoptions: {
noFloatOnDesktop: true,
noFloatOnMobile: true
}
```
> [Fix] Sticky Handler unpauses on video transition

- src/themes/_common/player/next.scss
ZIG-3663 text-of-stay-next-slightly-off-center-on-desktop
> fix on text center at next/stay buttons

- src/dynamics/ads_player/ads_player.html
- src/dynamics/ads_player/ads_player.js
I remove  the cover or overlap  on the player that prevent first click through  
> [ZIG-4834] fix clicking on the ads once instead of twice

- src/themes/_common/player/floating-with-sidebar.scss
Switched container to padding from margin to align container to fit exactly to size of sidebar
> ZIG-4904: Fix floating sidebar background color

- src/dynamics/video_player/player/player.js
-  Ignored the autoplaywhenvisible param when floatingonly is enable
-
-
> [ZIG-4788] ignored the autoplaywhenvisible param when floatingonly is enable

- src/themes/_common/player/adplayer.scss
- Set `z-index: 1` on ad container to stop ads from overlaying player controls.
- Removed unused styles
> [Fix] VPAID ad interface blocking player controls

- src/dynamics/video_player/player/player.js
- Adds functionality to render Companion banners to ad slots within the shadow DOM.
- Used by Video Kargo Player PR https://github.com/KargoGlobal/video-kargo-player/pull/541
- [] Added new unit, integration or regression tests
- [] Updated docs
- Let me know what docs need to be updated. 
- See https://github.com/KargoGlobal/video-kargo-player/pull/541
> KVID-594: Support fetching Companion ad slots from Shadow DOM

- src/dynamics/video_player/player/player.js
- Fix ads play muted when content is not
> [ZIG-5243] Fix ads play muted when content is not

- src/ads/ima/manager.js
- src/dynamics/ads_player/ads_player.html
- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/player.html
- src/themes/_common/player/player.scss
- Removes custom click tracking implementation. Here is [the ticket](https://kargo1.atlassian.net/browse/ZIG-5294) if you want more info.
- Adjust how `setDisableCustomPlaybackForIOS10Plus` is getting set. As of now, this would have to be set from the `video-kargo-player` config.js file. Not sure if this is something that customers set manually but nonetheless, the config name seemed wordy and we need to call this function for mobile skippable ads anyways: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/skippable-ads.
- I made the change in this repo but if preferred, can move it to `config.js` [here](https://github.com/KargoGlobal/video-kargo-player/blob/develop/src/player/configs.js#L46): and set a default value like:
```
"imasettings": {
"isMobile": …
```
> ZIG-5216: Remove custom click tracking element and fix inlinevastxml

- src/ads/ima/manager.js
- src/dynamics/ads_player/ads_player.html
- src/dynamics/ads_player/ads_player.js
- Adds support for custom click tracking element
- Adjust `sz` ad tag param check
- Show tooltips for ads only on Desktop
Demo page to test with is available in this [PR](https://github.com/KargoGlobal/video-kargo-player/pull/616) 
> [ZIG-5294] Add support for custom click tracking element

- src/dynamics/ads_player/ads_player.js
- Adds a check to make sure player is muted on `start`. VPAID creatives sometimes has syncing issues with content on start.
> [ZIG-5429] Address VPAID unmuting player during playback

- src/dynamics/video_player/player/states.js
- Adds a listener for `manualFallback` event. This is for our Longitude implementation specifically but the event is setup so it can be called outside of the Longitude implementation as well. 
Also review: https://github.com/KargoGlobal/video-kargo-player/pull/657
> [ZIG-5370] Add manual fallback listener (longitude)

- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
- Fixes a bug with outstream player crashing on `ad-error`
- Add logic to make the outstream player immediately request ads and not hide itself
- Add logic + config to retry ads on ad-error
- Make outstream always float with no sidebar
> [ZIG-5398] Outstream improvements

- src/dynamics/video_player/player/player.js
- Remove redundant logic for forcing outstream to always float with no side bar as it is [handled](https://github.com/KargoGlobal/video-kargo-player/pull/671) in `video-kargo-player` now.
> [ZIG-5453] Remove duplicate outstream cleanup logic

- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
- Had to refactor since `numOfRetriesOnError` set to 0 would not make ad requests immediate.
> [ZIG-5398] Refactor ad retry logic for outstream

- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
- Remove call to `hidePlayerContainer` in ad-error since the player gets hidden anyway. The extra call seemed to cause some side effects which resulted in the error shown in the ZIG ticket
> [ZIG-5613] Remove hidePlayerContainer on ad-error
