- README.md
- demos/playlist.html
- demos/themes/player/cube.html
- demos/themes/player/default.html
- demos/themes/player/elevate.html
- demos/themes/player/minimalist.html
- demos/themes/player/modern.html
- demos/themes/player/space.html
- demos/themes/player/theatre.html
- src/dynamics/video_player/player/player.js
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/cube/share.scss
- src/themes/video_player/default/controlbar.scss
- src/themes/video_player/default/share.scss
- src/themes/video_player/elevate/share.scss
- src/themes/video_player/minimalist/share.scss
- src/themes/video_player/modern/share.scss
- src/themes/video_player/space/controlbar.scss
- src/themes/video_player/space/share.scss
- src/themes/video_player/theatre/share.scss
Hi Oliver, 
Fix playlist, fix minor theme CSS bugs and change share transition settings.
> Fix playlist, fix minor theme css bugs and change share transition settings

- demos/playwhenvisible.html
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
Added play on visible functionality
> Added play on visible functionality

- demos/disablepauseseeking.html
- demos/themes/player/cube.html
- demos/themes/player/default.html
- demos/themes/player/elevate.html
- demos/themes/player/minimalist.html
- demos/themes/player/modern.html
- demos/themes/player/space.html
- demos/themes/player/theatre.html
- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/controlbar/video_player_controlbar.html
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/dynamics/video_recorder/recorder/states.js
- src/themes/common/mixins.scss
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/cube/cube-video_player_controlbar.html
- src/themes/video_player/default/controlbar.scss
- src/themes/video_player/default/player.scss
- src/themes/video_player/elevate/controlbar.scss
- src/themes/video_player/elevate/elevate-video_player_controlbar.html
- src/themes/video_player/minimalist/controlbar.scss
- src/themes/video_player/minimalist/minimalist-video_player_controlbar.html
- src/themes/video_player/modern/controlbar.scss
- src/themes/video_player/modern/modern-video_player_controlbar.html
- src/themes/video_player/space/controlbar.scss
- src/themes/video_player/space/space-video_player_controlbar.html
- src/themes/video_player/theatre/controlbar.scss
- src/themes/video_player/theatre/theatre-video_player_controlbar.html
Added pause and seeking disable functionality
> Added pause and seeking disable functionality

- Gruntfile.js
- demos/theme.html
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/default/controlbar.scss
- src/themes/video_player/elevate/colors.scss
- src/themes/video_player/elevate/controlbar.scss
- src/themes/video_player/elevate/theme.scss
- src/themes/video_player/minimalist/controlbar.scss
- src/themes/video_player/space/controlbar.scss
- src/themes/video_player/theatre/controlbar.scss
Fixed IE8 related css bugs in all themes
> Fix old ie issues

- src/dynamics/video_player/player/player.html
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/cube/cube-video_player_controlbar.html
- src/themes/video_player/default/controlbar.scss
- src/themes/video_player/elevate/controlbar.scss
- src/themes/video_player/minimalist/controlbar.scss
- src/themes/video_player/modern/controlbar.scss
- src/themes/video_player/modern/modern-video_player_controlbar.html
- src/themes/video_player/space/controlbar.scss
- src/themes/video_player/theatre/controlbar.scss
- src/themes/video_recorder/cube/controlbar.scss
- src/themes/video_recorder/default/controlbar.scss
- src/themes/video_recorder/elevate/controlbar.scss
- src/themes/video_recorder/minimalist/controlbar.scss
- src/themes/video_recorder/modern/chooser.scss
- src/themes/video_recorder/space/controlbar.scss
- src/themes/video_recorder/theatre/controlbar.scss
Removed tab focus outline from video overlay, restored focus outline style to default
> Removed tab focus outline from video overlay

- README.md
- demos/player-subtitle.html
- demos/tab-moves.html
- demos/themes.html
- package-source.json
- package.json
- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/controlbar/video_player_controlbar.html
- src/dynamics/video_player/playbutton/playbutton.html
- src/dynamics/video_player/playbutton/playbutton.js
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/themes/video_player/cube/cube-video_player_controlbar.html
- src/themes/video_player/cube/playbutton.scss
- src/themes/video_player/default/playbutton.scss
- src/themes/video_player/elevate/elevate-video_player_controlbar.html
- src/themes/video_player/elevate/playbutton.scss
- src/themes/video_player/minimalist/controlbar.scss
- src/themes/video_player/minimalist/minimalist-video_player_controlbar.html
- src/themes/video_player/minimalist/playbutton.scss
- src/themes/video_player/modern/modern-video_player_controlbar.html
- src/themes/video_player/modern/playbutton.scss
- src/themes/video_player/space/playbutton.scss
- src/themes/video_player/space/space-video_player_controlbar.html
- src/themes/video_player/space/space-video_player_playbutton.html
- src/themes/video_player/theatre/playbutton.scss
- src/themes/video_player/theatre/theatre-video_player_controlbar.html
Improved tab movement inside player
> Improved tab movement inside player

- README.md
- demos/simple3.html
- package-source.json
- package.json
- src/themes/image_viewer/cube/fullscreen.scss
- src/themes/image_viewer/default/fullscreen.scss
- src/themes/image_viewer/elevate/fullscreen.scss
- src/themes/image_viewer/minimalist/fullscreen.scss
- src/themes/image_viewer/modern/fullscreen.scss
- src/themes/image_viewer/space/fullscreen.scss
- src/themes/image_viewer/theatre/fullscreen.scss
- src/themes/video_player/cube/fullscreen.scss
- src/themes/video_player/default/fullscreen.scss
- src/themes/video_player/elevate/fullscreen.scss
- src/themes/video_player/minimalist/fullscreen.scss
- src/themes/video_player/modern/fullscreen.scss
- src/themes/video_player/space/fullscreen.scss
- src/themes/video_player/theatre/fullscreen.scss
Fixed Firefox and Chrome related fullscreen bugs
> Fix fullscreen bug

- README.md
- demos/theme.html
- package-source.json
- package.json
- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/controlbar/video_player_controlbar.html
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/default/controlbar.scss
Will prevent user interact with the player after some period which is 5000 ms by default
> Added feature restrict after some period

- README.md
- demos/playlist.html
- demos/ratio.html
- demos/themes/image-capture/cube.html
- demos/themes/image-capture/default.html
- demos/themes/image-capture/elevate.html
- demos/themes/image-capture/minimalist.html
- demos/themes/image-capture/modern.html
- demos/themes/image-capture/space.html
- demos/themes/image-capture/theatre.html
- demos/themes/player/default.html
- package-source.json
- package.json
- src/dynamics/_common/audio_visualisation.js
- src/dynamics/audio_player/player/player.js
- src/dynamics/audio_player/player/states.js
- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
- src/dynamics/video_player/tracks/video_player_tracks.html
1. Fixed Resolution calculation way based on the poster image
2. Fix bug related to track tags with `hidebarafter` option
3. Changed way auto-muting in Chromium-based browsers
> Fix image stretch

- README.md
- demos/mobile/recorder.html
- demos/ratio.html
- demos/themes/image-viewer/cube.html
- demos/themes/player/cube.html
- package-source.json
- package.json
- src/dynamics/_common/settings.js
- src/dynamics/image_viewer/viewer/image_viewer.js
- src/dynamics/video_player/player/player.js
- src/dynamics/video_recorder/chooser/chooser.js
- src/dynamics/video_recorder/chooser/video_recorder_chooser.html
- src/dynamics/video_recorder/recorder/recorder.html
- src/dynamics/video_recorder/recorder/recorder.js
- src/themes/audio_player/default/player.scss
- src/themes/image_viewer/default/viewer.scss
- src/themes/video_player/default/player.scss
- src/themes/video_recorder/_templates/video_recorder_chooser.html
- src/themes/video_recorder/cube/controlbar.scss
- src/themes/video_recorder/default/recorder.scss
1. Added `facecamera` attribute which is true by default for the mobile recorder
2. Fixed Player/Recorder/ImageViewer stretch related bugs
> Added mobile face camera default value fixed stretch related bugs

- README.md
- package-source.json
- package.json
- src/dynamics/image_capture/faceoutline/image_capture_faceoutline.html
- src/dynamics/video_recorder/faceoutline/video_recorder_faceoutline.html
- src/dynamics/video_recorder/recorder/recorder.html
Fixed face-outline position and recorder dimension setting related bug
> Fixed face-outline position and recorder dimension setting related bug

- README.md
- package-source.json
- package.json
- src/dynamics/video_recorder/recorder/states.js
Fixed IE/Edge cover-shot related bug also not supported video formats for all browsers
> Fixed Edge related and not supported video format bug

- README.md
- demos/assets/video-bgbb.vtt
- demos/playlist.html
- demos/themes/player/cube.html
- package-source.json
- package.json
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
1. Fixed after completing playlist, last only video play bug
2. Added `singleloop` feature for playlist ( Will be better also adding to control-bar, a. next track and b. repeat (single, all) buttons, maybe later shuttle)
3. Added new DYN trigger `last-playlist-item` if latest video playing from playlist. Could remove if not require.
> Fixed playlist start video and added playlist loop feature

- src/dynamics/video_player/player/player.js
Just disabled pip to be allowed by default
> default pip value - disabled

- src/dynamics/video_player/share/share.js
- src/dynamics/video_recorder/recorder/recorder.html
- src/dynamics/video_recorder/recorder/recorder.js
Updated Twitter share url and added `sharevideo` parameter to recorder player.
> Fix sharevideo

- src/locales/fr.yml
Replace "Revoir" with "Recommencer".
> Update French translation

- src/locales/es.yml
Updated spanish file, es.yml. Modified various translations, and added some that were missing too, as #127
> Updated spanish translation

- src/locales/de.yml
updated german translation with the latest strings from the original english file
> updated german translation 

- src/locales/it.yml
Updated italian translation with the latest strings from the original english file
> Updated italian translation

- src/locales/pt.yml
Updated some translations that were in pt-br and added new ones.
Please consider adding the hacktoberfest-accepted tag. Thanks!
> Update PT translations

- src/locales/fr.yml
> Update FR translations.

- src/locales/uk.yml
> Add Ukrainian translation

- src/locales/pl.yml
> Updated PL translations

- src/locales/tl.yml
For Issue #127 
Update TL translations
> Update TL translations

- src/locales/pt.yml
Updated some translations that I noticed could be improved.
Once again please consider adding the hacktoberfest-accepted tag. Thanks!
> Update some pt translations

- src/locales/it.yml
> Update and proofread Italian locale

- demos/embed/player.html
- src/dynamics/_common/audio_visualisation.js
- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/controlbar/video_player_controlbar.html
- src/dynamics/video_player/loader/video_player_loader.html
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
- src/dynamics/video_recorder/recorder/recorder.js
- src/themes/_common/style.scss
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/cube/cube-video_player_controlbar.html
- src/themes/video_player/default/player.scss
- src/themes/video_player/elevate/elevate-video_player_controlbar.html
- src/themes/video_player/minimalist/minimalist-video_player_controlbar.html
- src/themes/video_player/modern/modern-video_player_controlbar.html
- src/themes/video_player/space/controlbar.scss
- src/themes/video_player/space/space-video_player_controlbar.html
- src/themes/video_player/theatre/theatre-video_player_controlbar.html
Change the way fixing video jump bug, now seems more smooth and with no gradient.
Also added remaining time info, if user click on timer box.
> Change player placeholder

- demos/embed/player.html
- src/dynamics/_common/track_tags.js
- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/tracks/tracks.js
- src/dynamics/video_player/tracks/video_player_tracks.html
- src/themes/video_player/default/theme.scss
> Fixed Track tags related bugs

- src/locales/ro.yml
> update romanian translation

- src/dynamics/video_player/controlbar/controlbar.js
- src/dynamics/video_player/playbutton/playbutton.html
- src/dynamics/video_player/playbutton/playbutton.js
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/dynamics/video_recorder/recorder/recorder.html
- src/dynamics/video_recorder/recorder/recorder.js
- src/dynamics/video_recorder/recorder/states.js
- src/themes/video_player/_templates/video_player_playbutton.html
- src/themes/video_player/default/controlbar.scss
- src/themes/video_player/default/playbutton.scss
This PR adds a few improvements and bug fixes to video trimming.
> Updates on trimming

- src/dynamics/video_recorder/recorder/recorder.js
This PR introduces the following changes to the Video Recorder:
- Create method `imageUploaded` to check if image was uploaded
- Create method `audioUploaded` to check if audio was uploaded
> Feature: associated audio and image upload status

- src/dynamics/_common/audio_visualization.js
- src/dynamics/audio_player/player/player.js
- src/dynamics/audio_recorder/recorder/recorder.js
This PR fixes some issues related to audio visualization on the audio recorder and brings a few improvements to the AudioVisualization module.
> AudioVisualization bug fixes

- demos/embed/audio-player.html
- src/dynamics/audio_player/player/player.js
- src/dynamics/audio_player/player/states.js
This PR fixes issues related to autoplay on the audio player. It depends on the following PR: https://github.com/betajs/betajs-media/pull/60.
> Fix: AudioPlayer autoplay

- src/locales/it.yml
As requested in #127.
One string was wrong and a verb was not coherent with the tenses of the other ones.
> Fix minor Italian translation issues

- src/dynamics/video_recorder/recorder/recorder.js
- src/dynamics/video_recorder/recorder/states.js
Made minor renaming based on Bane request
> Made minor renaming

- .gitignore
- demos/ad-ima-player.html
- demos/embed/ad-ima-player.html
- demos/vast-samples/VAST_4_2/Inline_Companion_Tag-test.xml
- src/ads/ima/controllbar/controllbar.html
- src/ads/ima/controllbar/controllbar.js
- src/ads/ima/requester.js
- src/dynamics/video_player/adplayer/video_player_adplayer.html
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
- src/themes/_common/player/adplayer.scss
- src/themes/video_player/default/player.scss
1. Added companion ad 
2. Fixed resize player will resize ad container as well
3. Partially fixed multiple ad types (Linear and nonLinear) in pre-roll
> Added companion ad and fixed resize

- src/themes/video_player/cube/colors.scss
- src/themes/video_player/cube/controlbar.scss
- src/themes/video_player/elevate/colors.scss
- src/themes/video_player/elevate/controlbar.scss
- src/themes/video_player/minimalist/colors.scss
- src/themes/video_player/minimalist/controlbar.scss
- src/themes/video_player/space/colors.scss
- src/themes/video_player/space/controlbar.scss
- src/themes/video_player/theatre/colors.scss
- src/themes/video_player/theatre/controlbar.scss
Hi Oliver, this is the update to make the markers a bit more visible on trim screens
> marking the markers

- src/locales/el.yml
I add the missing lines on the el.yml with the greek translation
> Add missing greek translations to el.yml

- src/locales/ur.yml
Created a new file for Urdu Language & translated it into Urdu.
> Created ur.yml (Urdu Translation)

- src/dynamics/video_player/player/player.js
- src/themes/video_player/cube/theme.scss
- src/themes/video_player/default/theme.scss
- src/themes/video_player/elevate/theme.scss
- src/themes/video_player/minimalist/theme.scss
- src/themes/video_player/modern/theme.scss
- src/themes/video_player/space/theme.scss
- src/themes/video_player/theatre/theme.scss
Hi Oliver, this is to make the player take less than 100% width (without black borders), and with the linear ads showing properly.
> slim option

- src/dynamics/video_player/controlbar/controlbar.js
> Fix volume trigger

- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
This can be used to add a `next` button on the control bar.
> [Feature] [Video Player] hasnext attribute

- src/dynamics/video_player/player/player.js
Makes it easier to showcase features that are hidden by default, like the settings menu.
> [Feature] Configurable initial setting for active attributes

- src/dynamics/video_player/controlbar/video_player_controlbar.html
- src/dynamics/video_player/player/player.js
Reverts betajs/betajs-media-components#380
> Revert "Improve/make unmute only on player click"

- src/dynamics/video_player/player/player.js
- src/themes/video_player/default/fullscreen.scss
Reverts betajs/betajs-media-components#412
> Revert "Fix/fullscreen"

- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
This PR fixes the following issues:
- Value of `fullscreened` attribute on iOS
- Ad visibility when player is fullscreened on iOS
> [Fix] fullscreen on iOS

- src/themes/_common/player/next.scss
- src/themes/video_player/cube/fullscreen.scss
- src/themes/video_player/default/fullscreen.scss
Zig 3653/cutoff full screen on android
> Zig 3653/cutoff full screen on android

- src/ads/ima/manager.js
- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/player.js
Reverts betajs/betajs-media-components#458
I'm seeing some issues after merging with latest changes. 😬
> Revert "[Fix] Initial volume should match AdsRequest settings during ad playback"

- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/player.js
There are a few issues that need to be addressed before releasing this feature.
> Disable render frame on pause

- src/dynamics/ads_player/ads_player.html
- src/dynamics/ads_player/ads_player.js
- src/themes/_common/player/adplayer.scss
- [KVID-559](https://kargo1.atlassian.net/browse/KVID-559)
- Make learn more button have the same styling as the replay button
- Increase z index of the endcard buttons so it is clickable
- None
- None
- Learn more endcard button styling
- Proof that learn more button styling has been updated and can be clicked properly
- [Demo](https://drive.google.com/file/d/1wANzemvji0vodjB_-KD0ZJn453ddYwGG/view)
> style learn more button

- src/dynamics/ads_player/ads_player.html
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/tootip/tooltip.js
- src/dynamics/video_player/tootip/video_player_tooltip.html
- refactor on tooltips to be able to use a instance of it on kargo video
- https://github.com/KargoGlobal/video-kargo-player/pull/489
> refactor on tooltip to using a instance of it on kargo player instead

- src/ads/ima/manager.js
> ZIG-4586: Fix bug in companion backfill setting for google IMA sdk

- demos/mobile_player.html
- Created demo for the mobile version issue
- 
-
> [ZIG-4941]created mobile demo

- src/dynamics/video_player/player/player.js
> ZIG-4594: Fix bug where ads show "click to unmute" tooltip instead of "click to learn more"

- src/ads/ima/loader.js
- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/player.html
- src/dynamics/video_player/player/player.js
- Create `debug_ima` attribute for loading debug version of IMA SDK.
- Remove unused methods from `Ads.IMALoader` module.
> [Feature] Create debug_ima attribute

- src/dynamics/video_player/player/player.js
> [ZIG-5145]: Disable subtitles by default

- src/dynamics/video_player/player/player.js
- [-] Added new unit, integration or regression tests
- [-] Updated docs
> [ZIG-4762] Fix safari player not visible when there is ads

- .github/pull_request_template.md
Updated .github/pull_request_template.md file
> added local e2e pass checklist

- src/ads/ima/manager.js
- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/states.js
> ZIG-5256: Do not override size in adtagurl if defined

- src/dynamics/ads_player/ads_player.js
- src/dynamics/video_player/player/states.js
> Zig-5256 fix null url

- src/dynamics/ads_player/ads_controlbar/ads_controlbar.js
- src/dynamics/ads_player/ads_player.js
> ZIG-5219: Implement Duration Check in Video Player for VAST Ads

- src/dynamics/ads_player/ads_player.js
> ZIG-5219: Implement Duration Check in Video Player for VAST Ads fix

- src/dynamics/video_player/player/states.js
- tests/playwright/specs/player/autoplay.spec.js
- [*] Tested locally
- [] Added new unit, integration or regression tests
> zig 5269 remove autoscroll scroll up functionality

- package-lock.json
- src/dynamics/ads_player/ads_controlbar/ads_controlbar.js
- src/dynamics/ads_player/ads_player.js
Reverts:
* https://github.com/betajs/betajs-media-components/pull/597
* https://github.com/betajs/betajs-media-components/pull/594
> ZIG-5219: Revert ad duration check (ZIG-5219)

- src/dynamics/video_player/player/player.js
- src/dynamics/video_player/player/states.js
- tests/playwright/specs/headless/preload.spec.js
- tests/playwright/specs/player/autoplay.spec.js
- tests/playwright/specs/player/mid-postroll.spec.js
- tests/playwright/specs/player/player-unmute.spec.js
- tests/playwright/specs/player/preload.spec.js
https://github.com/KargoGlobal/video-kargo-player/pull/617
> ZIG-5273 stop running midrolls

- src/dynamics/video_player/player/player.js
> Zig 5165 fix next widget can not be turned off when sidebar gallery is shown

- src/ads/ima/manager.js
> set default numRedirect to 10

- src/dynamics/video_player/player/player.js
> zig 5434 Player fullscreen does not take up the whole screen on Android

- .github/actions/playwright-test/action.yml
- .github/workflows/CI.yml
- tests/playwright/config.js
- tests/playwright/utils/run-test.js
Fix CI flow, related to e2e test
> Fix: e2e test CI on BetaJS is broken

- tests/playwright/specs/headless/preload.spec.js
temporarily disabled testing manual play, as for now player used only with autoplay
> turned off manual play test on skipinitial

- src/dynamics/video_player/player/states.js
> ZIG-5572-auction-retry-happens-on-ad-error-immediately

- src/dynamics/ads_player/ads_player.js
> ZIG-5735: Fix companion ad rendering
